version: '3.7'
services:
    app:
        tty: true
        container_name: thrift-app
        build:
            context: .
            dockerfile: .docker/Dockerfile
            args:
                uid: ${HOST_UID}
        ports:
            - ${APP_HTTP_PORT}:80
        depends_on:
            - redis
    redis:
        container_name: thrift-redis
        image: redis:5.0.6-alpine
        ports:
            - ${REDIS_HOST_PORT}:6379
volumes:
    thriftredis:
        driver: local
